services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: ws-client
    hostname: client.walkscope.com
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - ./client/static:/app/static
      - ./client/vite.config.js:/app/vite.config.js
      - ./client/tsconfig.json:/app/tsconfig.json
      - ./client/svelte.config.js:/app/svelte.config.js
